name: Run tests

on:
  push:
    branches:
      - main
  pull_request:

permissions:
  contents: read

jobs:
  unit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/python_setup
      - run: make unit
  integration:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/python_setup
      - run: make integration
  acceptance:
    runs-on: ubuntu-latest
    env:
      LOKI_USERNAME: ${{ secrets.LOKI_USERNAME }}
      LOKI_PASSWORD: ${{ secrets.LOKI_PASSWORD }}
      LOKI_URL: ${{ secrets.LOKI_URL }}
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/python_setup
      - run: |
          docker compose up -d loki
          make acceptance
          docker compose down -v
