apiVersion: 1

datasources:
  - name: Loki
    type: loki
    access: proxy
    url: http://loki:3100
    basicAuth: true
    basicAuthUser: ${GRAFANA_LOKI_USER}
    secureJsonData:
      basicAuthPassword: ${GRAFANA_LOKI_PASSWORD}
    isDefault: true
    editable: true
